-- =============================================================================
-- 07_schedule.sql — The cycle runs itself
-- One root task checks for new filings daily; the chain fans out from there.
-- Each step logs its own outcome; a failed step does not block later steps.
-- =============================================================================

CREATE OR REPLACE TASK FCC_FILINGS.RAW.T_DAILY_CATALOG
  WAREHOUSE = FCC_WH
  SCHEDULE = 'USING CRON 0 4 * * * America/New_York'
AS
  CALL FCC_FILINGS.RAW.SP_CATALOG_STATION($STATION_CALL_SIGN, YEAR(CURRENT_DATE()));

CREATE OR REPLACE TASK FCC_FILINGS.RAW.T_DAILY_DOWNLOAD
  WAREHOUSE = FCC_WH
  AFTER FCC_FILINGS.RAW.T_DAILY_CATALOG
AS
  CALL FCC_FILINGS.RAW.SP_DOWNLOAD_BATCH(500);

CREATE OR REPLACE TASK FCC_FILINGS.PARSED.T_DAILY_PARSE
  WAREHOUSE = FCC_WH
  AFTER FCC_FILINGS.RAW.T_DAILY_DOWNLOAD
AS
  CALL FCC_FILINGS.PARSED.SP_PARSE_BATCH(500);

CREATE OR REPLACE TASK FCC_FILINGS.ANALYTICS.T_DAILY_EXTRACT
  WAREHOUSE = FCC_WH
  AFTER FCC_FILINGS.PARSED.T_DAILY_PARSE
AS
  CALL FCC_FILINGS.ANALYTICS.SP_EXTRACT_BATCH(500);

-- Resume the chain (tasks are created suspended)
ALTER TASK FCC_FILINGS.ANALYTICS.T_DAILY_EXTRACT RESUME;
ALTER TASK FCC_FILINGS.PARSED.T_DAILY_PARSE RESUME;
ALTER TASK FCC_FILINGS.RAW.T_DAILY_DOWNLOAD RESUME;
ALTER TASK FCC_FILINGS.RAW.T_DAILY_CATALOG RESUME;
